#! /bin/zsh -f

# Uncompress .als
git diff --cached --name-only --diff-filter=ACM | grep .als |
while read
do zcat -qf < $REPLY > .tmp && mv .tmp $REPLY && git add $_
done

# Generate dependencies.md
git/dependencies.command
