#! /bin/zsh -f

# Uncompress Ableton Live set
git diff --cached --name-only --diff-filter=ACM | grep .als |
while read
do zcat -qf < $REPLY > .tmp && mv .tmp $REPLY && git add $_
done

# Generate dependencies.md
git-ableton/dependencies.command
